### PR TITLE
Implement OVA

### PR DESCRIPTION
**Pull request by richlively**
Implement a roller for [OVA: The Anime Role-Playing Game](https://www.wiseturtle.com)

Basically you roll _x_ d6 dice. Each face is added to like faces i.e. all 1's are added together, all 2's, ... all 6's. The largest sum is the result. For example, if you roll 5 dice with three 4's, and two 5's, the result is 12.

Also handle rolling 0 and negative dice since that is part of the game system (character may have weaknesses or penalties).

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Thanks, will take a look a bit later :)

Have you checked the license on the dice images?

**Comment by richlively** [comment]
Thanks ;)

I have not checked on the license yet. I'm in the same discord server as the discord bot creator the images were taken from - let me ask them about it.

**Comment by richlively** [comment]
So BlueCorvid (discord bot creator) got the images from Clay (RPG author). I'm going to give Clay a few days to respond to my request to use the images. If not, I'll fall back to some public domain images.

**Comment by richlively** [comment]
Screenshot_20220201-001943
Should be good to go on the images

**Comment by richlively** [comment]
Shouldn't have any more to commit. Was just planning on updating the README after I got Clay's permission to use the images. But then I realized there were more HTML elements in `template.ts` than needed and might as well use the OVA images for the face result. So some quick changes to that. That should be the last of it (unless PR comments, of course)

**Comment by richlively** [comment]
Any update, @BernhardPosselt, on checking this? I don't want to rush you, just trying to plan out for my session next week. I am planning on using the OVA dice next weekend but can always use my build if it is not merged by then.

**Comment by BernhardPosselt** [comment]
Sry, week was hell xD

Looks good. I don't particularly like persisting state on the roller itself, but at least now with the current API, it's not possible to pass additional state to the template rendering function.

**Comment by richlively** [comment]
Hey no worries, life can get busy XD

Yeah, my first stab at it was just an attempt to make it work. In my polishing, I did not find a good place to store the `negative` state like you said :/

**Pull request merged**
